firebase_api_key: AAAAYRVVVts:APA91bEfvBS7VsOkbwEzBqL-u4KHwVh3bEpTd6lbTMWAEIfxn5ckeu0pZqupSicxPiX7qsqUj0YT8AjxwhWeKnj0Fm2xe8s9-0SmVqsKAI1xoMivz38xKDZ9hZqOGxjLiojGS9rkqvnh
admin_email: contacto.compra.directa@gmail.com
smtp_address: smtp.gmail.com
smtp_domain: gmail.com
smtp_port: 587
smtp_user_name: contacto.compra.directa@gmail.com
smtp_password: compra1234
